package com.greendao.manager;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.motor.administrator.DATAbase.greendao.TaskResEnity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK_RES_ENITY".
*/
public class TaskResEnityDao extends AbstractDao<TaskResEnity, Long> {

    public static final String TABLENAME = "TASK_RES_ENITY";

    /**
     * Properties of entity TaskResEnity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TaskId = new Property(1, Long.class, "taskId", false, "TASK_ID");
        public final static Property Csff = new Property(2, String.class, "csff", false, "CSFF");
        public final static Property SaveIndex = new Property(3, int.class, "saveIndex", false, "SAVE_INDEX");
        public final static Property SaveTime = new Property(4, String.class, "SaveTime", false, "SAVE_TIME");
        public final static Property Pjdy = new Property(5, double.class, "pjdy", false, "PJDY");
        public final static Property Pjdl = new Property(6, double.class, "pjdl", false, "PJDL");
        public final static Property Yggl = new Property(7, double.class, "yggl", false, "YGGL");
        public final static Property Wggl = new Property(8, double.class, "wggl", false, "WGGL");
        public final static Property Scgl = new Property(9, double.class, "scgl", false, "SCGL");
        public final static Property Glys = new Property(10, double.class, "glys", false, "GLYS");
        public final static Property Ygdn = new Property(11, double.class, "ygdn", false, "YGDN");
        public final static Property Wgdn = new Property(12, double.class, "wgdn", false, "WGDN");
        public final static Property Dwpl = new Property(13, double.class, "dwpl", false, "DWPL");
        public final static Property Szgl = new Property(14, double.class, "szgl", false, "SZGL");
        public final static Property Fzxs = new Property(15, double.class, "fzxs", false, "FZXS");
        public final static Property Zhxl = new Property(16, double.class, "zhxl", false, "ZHXL");
        public final static Property UAB = new Property(17, double.class, "UAB", false, "UAB");
        public final static Property UBC = new Property(18, double.class, "UBC", false, "UBC");
        public final static Property UCA = new Property(19, double.class, "UCA", false, "UCA");
        public final static Property Pjxdy = new Property(20, double.class, "pjxdy", false, "PJXDY");
        public final static Property UA = new Property(21, double.class, "UA", false, "UA");
        public final static Property UB = new Property(22, double.class, "UB", false, "UB");
        public final static Property UC = new Property(23, double.class, "UC", false, "UC");
        public final static Property IA = new Property(24, double.class, "IA", false, "IA");
        public final static Property IB = new Property(25, double.class, "IB", false, "IB");
        public final static Property IC = new Property(26, double.class, "IC", false, "IC");
        public final static Property Ayggl = new Property(27, double.class, "Ayggl", false, "AYGGL");
        public final static Property Byggl = new Property(28, double.class, "Byggl", false, "BYGGL");
        public final static Property Cyggl = new Property(29, double.class, "Cyggl", false, "CYGGL");
        public final static Property Awggl = new Property(30, double.class, "Awggl", false, "AWGGL");
        public final static Property Bwggl = new Property(31, double.class, "Bwggl", false, "BWGGL");
        public final static Property Cwggl = new Property(32, double.class, "Cwggl", false, "CWGGL");
        public final static Property Aszgl = new Property(33, double.class, "Aszgl", false, "ASZGL");
        public final static Property Bszgl = new Property(34, double.class, "Bszgl", false, "BSZGL");
        public final static Property Cszgl = new Property(35, double.class, "Cszgl", false, "CSZGL");
        public final static Property Aglys = new Property(36, double.class, "Aglys", false, "AGLYS");
        public final static Property Bglys = new Property(37, double.class, "Bglys", false, "BGLYS");
        public final static Property Cglys = new Property(38, double.class, "Cglys", false, "CGLYS");
        public final static Property PhUAB = new Property(39, double.class, "phUAB", false, "PH_UAB");
        public final static Property PhUBC = new Property(40, double.class, "phUBC", false, "PH_UBC");
        public final static Property PhUCA = new Property(41, double.class, "phUCA", false, "PH_UCA");
        public final static Property PhUIA = new Property(42, double.class, "phUIA", false, "PH_UIA");
        public final static Property PhUIB = new Property(43, double.class, "phUIB", false, "PH_UIB");
        public final static Property PhUIC = new Property(44, double.class, "phUIC", false, "PH_UIC");
        public final static Property Zhglsh = new Property(45, double.class, "zhglsh", false, "ZHGLSH");
        public final static Property Kzwggl = new Property(46, double.class, "kzwggl", false, "KZWGGL");
        public final static Property Edfzwggl = new Property(47, double.class, "edfzwggl", false, "EDFZWGGL");
        public final static Property Ygglsh = new Property(48, double.class, "ygglsh", false, "YGGLSH");
        public final static Property Edfzglsh = new Property(49, double.class, "edfzglsh", false, "EDFZGLSH");
        public final static Property Zhxhgl = new Property(50, double.class, "zhxhgl", false, "ZHXHGL");
        public final static Property Edzhxhgl = new Property(51, double.class, "edzhxhgl", false, "EDZHXHGL");
        public final static Property Edzhglsh = new Property(52, double.class, "edzhglsh", false, "EDZHGLSH");
        public final static Property Edzhxl = new Property(53, double.class, "edzhxl", false, "EDZHXL");
        public final static Property Wgbcrl = new Property(54, double.class, "wgbcrl", false, "WGBCRL");
        public final static Property Wgbcdrl = new Property(55, double.class, "wgbcdrl", false, "WGBCDRL");
        public final static Property Eddy = new Property(56, double.class, "eddy", false, "EDDY");
        public final static Property Eddl = new Property(57, double.class, "eddl", false, "EDDL");
        public final static Property Edxl = new Property(58, double.class, "edxl", false, "EDXL");
        public final static Property Edgl = new Property(59, double.class, "edgl", false, "EDGL");
        public final static Property Kzgl = new Property(60, double.class, "kzgl", false, "KZGL");
        public final static Property Kzdl = new Property(61, double.class, "kzdl", false, "KZDL");
        public final static Property Edglys = new Property(62, double.class, "edglys", false, "EDGLYS");
        public final static Property Wgjjdl = new Property(63, double.class, "wgjjdl", false, "WGJJDL");
        public final static Property Djyxzt = new Property(64, double.class, "djyxzt", false, "DJYXZT");
        public final static Property Dypc = new Property(65, double.class, "dypc", false, "DYPC");
        public final static Property Sxbphd = new Property(66, double.class, "sxbphd", false, "SXBPHD");
        public final static Property Mbglys = new Property(67, double.class, "mbglys", false, "MBGLYS");
        public final static Property Wd = new Property(68, double.class, "wd", false, "WD");
        public final static Property Sd = new Property(69, double.class, "sd", false, "SD");
        public final static Property Dqy = new Property(70, double.class, "dqy", false, "DQY");
        public final static Property Date = new Property(71, double.class, "date", false, "DATE");
        public final static Property Savedate = new Property(72, double.class, "savedate", false, "SAVEDATE");
        public final static Property Js = new Property(73, int.class, "js", false, "JS");
        public final static Property Lxdl = new Property(74, double.class, "lxdl", false, "LXDL");
        public final static Property KUA = new Property(75, double.class, "KUA", false, "KUA");
        public final static Property KUB = new Property(76, double.class, "KUB", false, "KUB");
        public final static Property KUC = new Property(77, double.class, "KUC", false, "KUC");
        public final static Property KIA = new Property(78, double.class, "KIA", false, "KIA");
        public final static Property KIB = new Property(79, double.class, "KIB", false, "KIB");
        public final static Property KIC = new Property(80, double.class, "KIC", false, "KIC");
        public final static Property HCUA = new Property(81, double.class, "HCUA", false, "HCUA");
        public final static Property HCUB = new Property(82, double.class, "HCUB", false, "HCUB");
        public final static Property HCUC = new Property(83, double.class, "HCUC", false, "HCUC");
        public final static Property HCIA = new Property(84, double.class, "HCIA", false, "HCIA");
        public final static Property HCIB = new Property(85, double.class, "HCIB", false, "HCIB");
        public final static Property HCIC = new Property(86, double.class, "HCIC", false, "HCIC");
        public final static Property By1 = new Property(87, double.class, "by1", false, "BY1");
        public final static Property By2 = new Property(88, double.class, "by2", false, "BY2");
        public final static Property By3 = new Property(89, double.class, "by3", false, "BY3");
        public final static Property By4 = new Property(90, double.class, "by4", false, "BY4");
        public final static Property By5 = new Property(91, double.class, "by5", false, "BY5");
        public final static Property By6 = new Property(92, double.class, "by6", false, "BY6");
        public final static Property By7 = new Property(93, double.class, "by7", false, "BY7");
        public final static Property By8 = new Property(94, double.class, "by8", false, "BY8");
        public final static Property By9 = new Property(95, double.class, "by9", false, "BY9");
        public final static Property By10 = new Property(96, double.class, "by10", false, "BY10");
        public final static Property Dybb = new Property(97, double.class, "dybb", false, "DYBB");
        public final static Property Dlbb = new Property(98, double.class, "dlbb", false, "DLBB");
        public final static Property Method = new Property(99, int.class, "method", false, "METHOD");
        public final static Property Xl = new Property(100, double.class, "xl", false, "XL");
    }


    public TaskResEnityDao(DaoConfig config) {
        super(config);
    }
    
    public TaskResEnityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK_RES_ENITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TASK_ID\" INTEGER," + // 1: taskId
                "\"CSFF\" TEXT," + // 2: csff
                "\"SAVE_INDEX\" INTEGER NOT NULL ," + // 3: saveIndex
                "\"SAVE_TIME\" TEXT," + // 4: SaveTime
                "\"PJDY\" REAL NOT NULL ," + // 5: pjdy
                "\"PJDL\" REAL NOT NULL ," + // 6: pjdl
                "\"YGGL\" REAL NOT NULL ," + // 7: yggl
                "\"WGGL\" REAL NOT NULL ," + // 8: wggl
                "\"SCGL\" REAL NOT NULL ," + // 9: scgl
                "\"GLYS\" REAL NOT NULL ," + // 10: glys
                "\"YGDN\" REAL NOT NULL ," + // 11: ygdn
                "\"WGDN\" REAL NOT NULL ," + // 12: wgdn
                "\"DWPL\" REAL NOT NULL ," + // 13: dwpl
                "\"SZGL\" REAL NOT NULL ," + // 14: szgl
                "\"FZXS\" REAL NOT NULL ," + // 15: fzxs
                "\"ZHXL\" REAL NOT NULL ," + // 16: zhxl
                "\"UAB\" REAL NOT NULL ," + // 17: UAB
                "\"UBC\" REAL NOT NULL ," + // 18: UBC
                "\"UCA\" REAL NOT NULL ," + // 19: UCA
                "\"PJXDY\" REAL NOT NULL ," + // 20: pjxdy
                "\"UA\" REAL NOT NULL ," + // 21: UA
                "\"UB\" REAL NOT NULL ," + // 22: UB
                "\"UC\" REAL NOT NULL ," + // 23: UC
                "\"IA\" REAL NOT NULL ," + // 24: IA
                "\"IB\" REAL NOT NULL ," + // 25: IB
                "\"IC\" REAL NOT NULL ," + // 26: IC
                "\"AYGGL\" REAL NOT NULL ," + // 27: Ayggl
                "\"BYGGL\" REAL NOT NULL ," + // 28: Byggl
                "\"CYGGL\" REAL NOT NULL ," + // 29: Cyggl
                "\"AWGGL\" REAL NOT NULL ," + // 30: Awggl
                "\"BWGGL\" REAL NOT NULL ," + // 31: Bwggl
                "\"CWGGL\" REAL NOT NULL ," + // 32: Cwggl
                "\"ASZGL\" REAL NOT NULL ," + // 33: Aszgl
                "\"BSZGL\" REAL NOT NULL ," + // 34: Bszgl
                "\"CSZGL\" REAL NOT NULL ," + // 35: Cszgl
                "\"AGLYS\" REAL NOT NULL ," + // 36: Aglys
                "\"BGLYS\" REAL NOT NULL ," + // 37: Bglys
                "\"CGLYS\" REAL NOT NULL ," + // 38: Cglys
                "\"PH_UAB\" REAL NOT NULL ," + // 39: phUAB
                "\"PH_UBC\" REAL NOT NULL ," + // 40: phUBC
                "\"PH_UCA\" REAL NOT NULL ," + // 41: phUCA
                "\"PH_UIA\" REAL NOT NULL ," + // 42: phUIA
                "\"PH_UIB\" REAL NOT NULL ," + // 43: phUIB
                "\"PH_UIC\" REAL NOT NULL ," + // 44: phUIC
                "\"ZHGLSH\" REAL NOT NULL ," + // 45: zhglsh
                "\"KZWGGL\" REAL NOT NULL ," + // 46: kzwggl
                "\"EDFZWGGL\" REAL NOT NULL ," + // 47: edfzwggl
                "\"YGGLSH\" REAL NOT NULL ," + // 48: ygglsh
                "\"EDFZGLSH\" REAL NOT NULL ," + // 49: edfzglsh
                "\"ZHXHGL\" REAL NOT NULL ," + // 50: zhxhgl
                "\"EDZHXHGL\" REAL NOT NULL ," + // 51: edzhxhgl
                "\"EDZHGLSH\" REAL NOT NULL ," + // 52: edzhglsh
                "\"EDZHXL\" REAL NOT NULL ," + // 53: edzhxl
                "\"WGBCRL\" REAL NOT NULL ," + // 54: wgbcrl
                "\"WGBCDRL\" REAL NOT NULL ," + // 55: wgbcdrl
                "\"EDDY\" REAL NOT NULL ," + // 56: eddy
                "\"EDDL\" REAL NOT NULL ," + // 57: eddl
                "\"EDXL\" REAL NOT NULL ," + // 58: edxl
                "\"EDGL\" REAL NOT NULL ," + // 59: edgl
                "\"KZGL\" REAL NOT NULL ," + // 60: kzgl
                "\"KZDL\" REAL NOT NULL ," + // 61: kzdl
                "\"EDGLYS\" REAL NOT NULL ," + // 62: edglys
                "\"WGJJDL\" REAL NOT NULL ," + // 63: wgjjdl
                "\"DJYXZT\" REAL NOT NULL ," + // 64: djyxzt
                "\"DYPC\" REAL NOT NULL ," + // 65: dypc
                "\"SXBPHD\" REAL NOT NULL ," + // 66: sxbphd
                "\"MBGLYS\" REAL NOT NULL ," + // 67: mbglys
                "\"WD\" REAL NOT NULL ," + // 68: wd
                "\"SD\" REAL NOT NULL ," + // 69: sd
                "\"DQY\" REAL NOT NULL ," + // 70: dqy
                "\"DATE\" REAL NOT NULL ," + // 71: date
                "\"SAVEDATE\" REAL NOT NULL ," + // 72: savedate
                "\"JS\" INTEGER NOT NULL ," + // 73: js
                "\"LXDL\" REAL NOT NULL ," + // 74: lxdl
                "\"KUA\" REAL NOT NULL ," + // 75: KUA
                "\"KUB\" REAL NOT NULL ," + // 76: KUB
                "\"KUC\" REAL NOT NULL ," + // 77: KUC
                "\"KIA\" REAL NOT NULL ," + // 78: KIA
                "\"KIB\" REAL NOT NULL ," + // 79: KIB
                "\"KIC\" REAL NOT NULL ," + // 80: KIC
                "\"HCUA\" REAL NOT NULL ," + // 81: HCUA
                "\"HCUB\" REAL NOT NULL ," + // 82: HCUB
                "\"HCUC\" REAL NOT NULL ," + // 83: HCUC
                "\"HCIA\" REAL NOT NULL ," + // 84: HCIA
                "\"HCIB\" REAL NOT NULL ," + // 85: HCIB
                "\"HCIC\" REAL NOT NULL ," + // 86: HCIC
                "\"BY1\" REAL NOT NULL ," + // 87: by1
                "\"BY2\" REAL NOT NULL ," + // 88: by2
                "\"BY3\" REAL NOT NULL ," + // 89: by3
                "\"BY4\" REAL NOT NULL ," + // 90: by4
                "\"BY5\" REAL NOT NULL ," + // 91: by5
                "\"BY6\" REAL NOT NULL ," + // 92: by6
                "\"BY7\" REAL NOT NULL ," + // 93: by7
                "\"BY8\" REAL NOT NULL ," + // 94: by8
                "\"BY9\" REAL NOT NULL ," + // 95: by9
                "\"BY10\" REAL NOT NULL ," + // 96: by10
                "\"DYBB\" REAL NOT NULL ," + // 97: dybb
                "\"DLBB\" REAL NOT NULL ," + // 98: dlbb
                "\"METHOD\" INTEGER NOT NULL ," + // 99: method
                "\"XL\" REAL NOT NULL );"); // 100: xl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK_RES_ENITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TaskResEnity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long taskId = entity.getTaskId();
        if (taskId != null) {
            stmt.bindLong(2, taskId);
        }
 
        String csff = entity.getCsff();
        if (csff != null) {
            stmt.bindString(3, csff);
        }
        stmt.bindLong(4, entity.getSaveIndex());
 
        String SaveTime = entity.getSaveTime();
        if (SaveTime != null) {
            stmt.bindString(5, SaveTime);
        }
        stmt.bindDouble(6, entity.getPjdy());
        stmt.bindDouble(7, entity.getPjdl());
        stmt.bindDouble(8, entity.getYggl());
        stmt.bindDouble(9, entity.getWggl());
        stmt.bindDouble(10, entity.getScgl());
        stmt.bindDouble(11, entity.getGlys());
        stmt.bindDouble(12, entity.getYgdn());
        stmt.bindDouble(13, entity.getWgdn());
        stmt.bindDouble(14, entity.getDwpl());
        stmt.bindDouble(15, entity.getSzgl());
        stmt.bindDouble(16, entity.getFzxs());
        stmt.bindDouble(17, entity.getZhxl());
        stmt.bindDouble(18, entity.getUAB());
        stmt.bindDouble(19, entity.getUBC());
        stmt.bindDouble(20, entity.getUCA());
        stmt.bindDouble(21, entity.getPjxdy());
        stmt.bindDouble(22, entity.getUA());
        stmt.bindDouble(23, entity.getUB());
        stmt.bindDouble(24, entity.getUC());
        stmt.bindDouble(25, entity.getIA());
        stmt.bindDouble(26, entity.getIB());
        stmt.bindDouble(27, entity.getIC());
        stmt.bindDouble(28, entity.getAyggl());
        stmt.bindDouble(29, entity.getByggl());
        stmt.bindDouble(30, entity.getCyggl());
        stmt.bindDouble(31, entity.getAwggl());
        stmt.bindDouble(32, entity.getBwggl());
        stmt.bindDouble(33, entity.getCwggl());
        stmt.bindDouble(34, entity.getAszgl());
        stmt.bindDouble(35, entity.getBszgl());
        stmt.bindDouble(36, entity.getCszgl());
        stmt.bindDouble(37, entity.getAglys());
        stmt.bindDouble(38, entity.getBglys());
        stmt.bindDouble(39, entity.getCglys());
        stmt.bindDouble(40, entity.getPhUAB());
        stmt.bindDouble(41, entity.getPhUBC());
        stmt.bindDouble(42, entity.getPhUCA());
        stmt.bindDouble(43, entity.getPhUIA());
        stmt.bindDouble(44, entity.getPhUIB());
        stmt.bindDouble(45, entity.getPhUIC());
        stmt.bindDouble(46, entity.getZhglsh());
        stmt.bindDouble(47, entity.getKzwggl());
        stmt.bindDouble(48, entity.getEdfzwggl());
        stmt.bindDouble(49, entity.getYgglsh());
        stmt.bindDouble(50, entity.getEdfzglsh());
        stmt.bindDouble(51, entity.getZhxhgl());
        stmt.bindDouble(52, entity.getEdzhxhgl());
        stmt.bindDouble(53, entity.getEdzhglsh());
        stmt.bindDouble(54, entity.getEdzhxl());
        stmt.bindDouble(55, entity.getWgbcrl());
        stmt.bindDouble(56, entity.getWgbcdrl());
        stmt.bindDouble(57, entity.getEddy());
        stmt.bindDouble(58, entity.getEddl());
        stmt.bindDouble(59, entity.getEdxl());
        stmt.bindDouble(60, entity.getEdgl());
        stmt.bindDouble(61, entity.getKzgl());
        stmt.bindDouble(62, entity.getKzdl());
        stmt.bindDouble(63, entity.getEdglys());
        stmt.bindDouble(64, entity.getWgjjdl());
        stmt.bindDouble(65, entity.getDjyxzt());
        stmt.bindDouble(66, entity.getDypc());
        stmt.bindDouble(67, entity.getSxbphd());
        stmt.bindDouble(68, entity.getMbglys());
        stmt.bindDouble(69, entity.getWd());
        stmt.bindDouble(70, entity.getSd());
        stmt.bindDouble(71, entity.getDqy());
        stmt.bindDouble(72, entity.getDate());
        stmt.bindDouble(73, entity.getSavedate());
        stmt.bindLong(74, entity.getJs());
        stmt.bindDouble(75, entity.getLxdl());
        stmt.bindDouble(76, entity.getKUA());
        stmt.bindDouble(77, entity.getKUB());
        stmt.bindDouble(78, entity.getKUC());
        stmt.bindDouble(79, entity.getKIA());
        stmt.bindDouble(80, entity.getKIB());
        stmt.bindDouble(81, entity.getKIC());
        stmt.bindDouble(82, entity.getHCUA());
        stmt.bindDouble(83, entity.getHCUB());
        stmt.bindDouble(84, entity.getHCUC());
        stmt.bindDouble(85, entity.getHCIA());
        stmt.bindDouble(86, entity.getHCIB());
        stmt.bindDouble(87, entity.getHCIC());
        stmt.bindDouble(88, entity.getBy1());
        stmt.bindDouble(89, entity.getBy2());
        stmt.bindDouble(90, entity.getBy3());
        stmt.bindDouble(91, entity.getBy4());
        stmt.bindDouble(92, entity.getBy5());
        stmt.bindDouble(93, entity.getBy6());
        stmt.bindDouble(94, entity.getBy7());
        stmt.bindDouble(95, entity.getBy8());
        stmt.bindDouble(96, entity.getBy9());
        stmt.bindDouble(97, entity.getBy10());
        stmt.bindDouble(98, entity.getDybb());
        stmt.bindDouble(99, entity.getDlbb());
        stmt.bindLong(100, entity.getMethod());
        stmt.bindDouble(101, entity.getXl());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TaskResEnity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long taskId = entity.getTaskId();
        if (taskId != null) {
            stmt.bindLong(2, taskId);
        }
 
        String csff = entity.getCsff();
        if (csff != null) {
            stmt.bindString(3, csff);
        }
        stmt.bindLong(4, entity.getSaveIndex());
 
        String SaveTime = entity.getSaveTime();
        if (SaveTime != null) {
            stmt.bindString(5, SaveTime);
        }
        stmt.bindDouble(6, entity.getPjdy());
        stmt.bindDouble(7, entity.getPjdl());
        stmt.bindDouble(8, entity.getYggl());
        stmt.bindDouble(9, entity.getWggl());
        stmt.bindDouble(10, entity.getScgl());
        stmt.bindDouble(11, entity.getGlys());
        stmt.bindDouble(12, entity.getYgdn());
        stmt.bindDouble(13, entity.getWgdn());
        stmt.bindDouble(14, entity.getDwpl());
        stmt.bindDouble(15, entity.getSzgl());
        stmt.bindDouble(16, entity.getFzxs());
        stmt.bindDouble(17, entity.getZhxl());
        stmt.bindDouble(18, entity.getUAB());
        stmt.bindDouble(19, entity.getUBC());
        stmt.bindDouble(20, entity.getUCA());
        stmt.bindDouble(21, entity.getPjxdy());
        stmt.bindDouble(22, entity.getUA());
        stmt.bindDouble(23, entity.getUB());
        stmt.bindDouble(24, entity.getUC());
        stmt.bindDouble(25, entity.getIA());
        stmt.bindDouble(26, entity.getIB());
        stmt.bindDouble(27, entity.getIC());
        stmt.bindDouble(28, entity.getAyggl());
        stmt.bindDouble(29, entity.getByggl());
        stmt.bindDouble(30, entity.getCyggl());
        stmt.bindDouble(31, entity.getAwggl());
        stmt.bindDouble(32, entity.getBwggl());
        stmt.bindDouble(33, entity.getCwggl());
        stmt.bindDouble(34, entity.getAszgl());
        stmt.bindDouble(35, entity.getBszgl());
        stmt.bindDouble(36, entity.getCszgl());
        stmt.bindDouble(37, entity.getAglys());
        stmt.bindDouble(38, entity.getBglys());
        stmt.bindDouble(39, entity.getCglys());
        stmt.bindDouble(40, entity.getPhUAB());
        stmt.bindDouble(41, entity.getPhUBC());
        stmt.bindDouble(42, entity.getPhUCA());
        stmt.bindDouble(43, entity.getPhUIA());
        stmt.bindDouble(44, entity.getPhUIB());
        stmt.bindDouble(45, entity.getPhUIC());
        stmt.bindDouble(46, entity.getZhglsh());
        stmt.bindDouble(47, entity.getKzwggl());
        stmt.bindDouble(48, entity.getEdfzwggl());
        stmt.bindDouble(49, entity.getYgglsh());
        stmt.bindDouble(50, entity.getEdfzglsh());
        stmt.bindDouble(51, entity.getZhxhgl());
        stmt.bindDouble(52, entity.getEdzhxhgl());
        stmt.bindDouble(53, entity.getEdzhglsh());
        stmt.bindDouble(54, entity.getEdzhxl());
        stmt.bindDouble(55, entity.getWgbcrl());
        stmt.bindDouble(56, entity.getWgbcdrl());
        stmt.bindDouble(57, entity.getEddy());
        stmt.bindDouble(58, entity.getEddl());
        stmt.bindDouble(59, entity.getEdxl());
        stmt.bindDouble(60, entity.getEdgl());
        stmt.bindDouble(61, entity.getKzgl());
        stmt.bindDouble(62, entity.getKzdl());
        stmt.bindDouble(63, entity.getEdglys());
        stmt.bindDouble(64, entity.getWgjjdl());
        stmt.bindDouble(65, entity.getDjyxzt());
        stmt.bindDouble(66, entity.getDypc());
        stmt.bindDouble(67, entity.getSxbphd());
        stmt.bindDouble(68, entity.getMbglys());
        stmt.bindDouble(69, entity.getWd());
        stmt.bindDouble(70, entity.getSd());
        stmt.bindDouble(71, entity.getDqy());
        stmt.bindDouble(72, entity.getDate());
        stmt.bindDouble(73, entity.getSavedate());
        stmt.bindLong(74, entity.getJs());
        stmt.bindDouble(75, entity.getLxdl());
        stmt.bindDouble(76, entity.getKUA());
        stmt.bindDouble(77, entity.getKUB());
        stmt.bindDouble(78, entity.getKUC());
        stmt.bindDouble(79, entity.getKIA());
        stmt.bindDouble(80, entity.getKIB());
        stmt.bindDouble(81, entity.getKIC());
        stmt.bindDouble(82, entity.getHCUA());
        stmt.bindDouble(83, entity.getHCUB());
        stmt.bindDouble(84, entity.getHCUC());
        stmt.bindDouble(85, entity.getHCIA());
        stmt.bindDouble(86, entity.getHCIB());
        stmt.bindDouble(87, entity.getHCIC());
        stmt.bindDouble(88, entity.getBy1());
        stmt.bindDouble(89, entity.getBy2());
        stmt.bindDouble(90, entity.getBy3());
        stmt.bindDouble(91, entity.getBy4());
        stmt.bindDouble(92, entity.getBy5());
        stmt.bindDouble(93, entity.getBy6());
        stmt.bindDouble(94, entity.getBy7());
        stmt.bindDouble(95, entity.getBy8());
        stmt.bindDouble(96, entity.getBy9());
        stmt.bindDouble(97, entity.getBy10());
        stmt.bindDouble(98, entity.getDybb());
        stmt.bindDouble(99, entity.getDlbb());
        stmt.bindLong(100, entity.getMethod());
        stmt.bindDouble(101, entity.getXl());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TaskResEnity readEntity(Cursor cursor, int offset) {
        TaskResEnity entity = new TaskResEnity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // taskId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // csff
            cursor.getInt(offset + 3), // saveIndex
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // SaveTime
            cursor.getDouble(offset + 5), // pjdy
            cursor.getDouble(offset + 6), // pjdl
            cursor.getDouble(offset + 7), // yggl
            cursor.getDouble(offset + 8), // wggl
            cursor.getDouble(offset + 9), // scgl
            cursor.getDouble(offset + 10), // glys
            cursor.getDouble(offset + 11), // ygdn
            cursor.getDouble(offset + 12), // wgdn
            cursor.getDouble(offset + 13), // dwpl
            cursor.getDouble(offset + 14), // szgl
            cursor.getDouble(offset + 15), // fzxs
            cursor.getDouble(offset + 16), // zhxl
            cursor.getDouble(offset + 17), // UAB
            cursor.getDouble(offset + 18), // UBC
            cursor.getDouble(offset + 19), // UCA
            cursor.getDouble(offset + 20), // pjxdy
            cursor.getDouble(offset + 21), // UA
            cursor.getDouble(offset + 22), // UB
            cursor.getDouble(offset + 23), // UC
            cursor.getDouble(offset + 24), // IA
            cursor.getDouble(offset + 25), // IB
            cursor.getDouble(offset + 26), // IC
            cursor.getDouble(offset + 27), // Ayggl
            cursor.getDouble(offset + 28), // Byggl
            cursor.getDouble(offset + 29), // Cyggl
            cursor.getDouble(offset + 30), // Awggl
            cursor.getDouble(offset + 31), // Bwggl
            cursor.getDouble(offset + 32), // Cwggl
            cursor.getDouble(offset + 33), // Aszgl
            cursor.getDouble(offset + 34), // Bszgl
            cursor.getDouble(offset + 35), // Cszgl
            cursor.getDouble(offset + 36), // Aglys
            cursor.getDouble(offset + 37), // Bglys
            cursor.getDouble(offset + 38), // Cglys
            cursor.getDouble(offset + 39), // phUAB
            cursor.getDouble(offset + 40), // phUBC
            cursor.getDouble(offset + 41), // phUCA
            cursor.getDouble(offset + 42), // phUIA
            cursor.getDouble(offset + 43), // phUIB
            cursor.getDouble(offset + 44), // phUIC
            cursor.getDouble(offset + 45), // zhglsh
            cursor.getDouble(offset + 46), // kzwggl
            cursor.getDouble(offset + 47), // edfzwggl
            cursor.getDouble(offset + 48), // ygglsh
            cursor.getDouble(offset + 49), // edfzglsh
            cursor.getDouble(offset + 50), // zhxhgl
            cursor.getDouble(offset + 51), // edzhxhgl
            cursor.getDouble(offset + 52), // edzhglsh
            cursor.getDouble(offset + 53), // edzhxl
            cursor.getDouble(offset + 54), // wgbcrl
            cursor.getDouble(offset + 55), // wgbcdrl
            cursor.getDouble(offset + 56), // eddy
            cursor.getDouble(offset + 57), // eddl
            cursor.getDouble(offset + 58), // edxl
            cursor.getDouble(offset + 59), // edgl
            cursor.getDouble(offset + 60), // kzgl
            cursor.getDouble(offset + 61), // kzdl
            cursor.getDouble(offset + 62), // edglys
            cursor.getDouble(offset + 63), // wgjjdl
            cursor.getDouble(offset + 64), // djyxzt
            cursor.getDouble(offset + 65), // dypc
            cursor.getDouble(offset + 66), // sxbphd
            cursor.getDouble(offset + 67), // mbglys
            cursor.getDouble(offset + 68), // wd
            cursor.getDouble(offset + 69), // sd
            cursor.getDouble(offset + 70), // dqy
            cursor.getDouble(offset + 71), // date
            cursor.getDouble(offset + 72), // savedate
            cursor.getInt(offset + 73), // js
            cursor.getDouble(offset + 74), // lxdl
            cursor.getDouble(offset + 75), // KUA
            cursor.getDouble(offset + 76), // KUB
            cursor.getDouble(offset + 77), // KUC
            cursor.getDouble(offset + 78), // KIA
            cursor.getDouble(offset + 79), // KIB
            cursor.getDouble(offset + 80), // KIC
            cursor.getDouble(offset + 81), // HCUA
            cursor.getDouble(offset + 82), // HCUB
            cursor.getDouble(offset + 83), // HCUC
            cursor.getDouble(offset + 84), // HCIA
            cursor.getDouble(offset + 85), // HCIB
            cursor.getDouble(offset + 86), // HCIC
            cursor.getDouble(offset + 87), // by1
            cursor.getDouble(offset + 88), // by2
            cursor.getDouble(offset + 89), // by3
            cursor.getDouble(offset + 90), // by4
            cursor.getDouble(offset + 91), // by5
            cursor.getDouble(offset + 92), // by6
            cursor.getDouble(offset + 93), // by7
            cursor.getDouble(offset + 94), // by8
            cursor.getDouble(offset + 95), // by9
            cursor.getDouble(offset + 96), // by10
            cursor.getDouble(offset + 97), // dybb
            cursor.getDouble(offset + 98), // dlbb
            cursor.getInt(offset + 99), // method
            cursor.getDouble(offset + 100) // xl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TaskResEnity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTaskId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCsff(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSaveIndex(cursor.getInt(offset + 3));
        entity.setSaveTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPjdy(cursor.getDouble(offset + 5));
        entity.setPjdl(cursor.getDouble(offset + 6));
        entity.setYggl(cursor.getDouble(offset + 7));
        entity.setWggl(cursor.getDouble(offset + 8));
        entity.setScgl(cursor.getDouble(offset + 9));
        entity.setGlys(cursor.getDouble(offset + 10));
        entity.setYgdn(cursor.getDouble(offset + 11));
        entity.setWgdn(cursor.getDouble(offset + 12));
        entity.setDwpl(cursor.getDouble(offset + 13));
        entity.setSzgl(cursor.getDouble(offset + 14));
        entity.setFzxs(cursor.getDouble(offset + 15));
        entity.setZhxl(cursor.getDouble(offset + 16));
        entity.setUAB(cursor.getDouble(offset + 17));
        entity.setUBC(cursor.getDouble(offset + 18));
        entity.setUCA(cursor.getDouble(offset + 19));
        entity.setPjxdy(cursor.getDouble(offset + 20));
        entity.setUA(cursor.getDouble(offset + 21));
        entity.setUB(cursor.getDouble(offset + 22));
        entity.setUC(cursor.getDouble(offset + 23));
        entity.setIA(cursor.getDouble(offset + 24));
        entity.setIB(cursor.getDouble(offset + 25));
        entity.setIC(cursor.getDouble(offset + 26));
        entity.setAyggl(cursor.getDouble(offset + 27));
        entity.setByggl(cursor.getDouble(offset + 28));
        entity.setCyggl(cursor.getDouble(offset + 29));
        entity.setAwggl(cursor.getDouble(offset + 30));
        entity.setBwggl(cursor.getDouble(offset + 31));
        entity.setCwggl(cursor.getDouble(offset + 32));
        entity.setAszgl(cursor.getDouble(offset + 33));
        entity.setBszgl(cursor.getDouble(offset + 34));
        entity.setCszgl(cursor.getDouble(offset + 35));
        entity.setAglys(cursor.getDouble(offset + 36));
        entity.setBglys(cursor.getDouble(offset + 37));
        entity.setCglys(cursor.getDouble(offset + 38));
        entity.setPhUAB(cursor.getDouble(offset + 39));
        entity.setPhUBC(cursor.getDouble(offset + 40));
        entity.setPhUCA(cursor.getDouble(offset + 41));
        entity.setPhUIA(cursor.getDouble(offset + 42));
        entity.setPhUIB(cursor.getDouble(offset + 43));
        entity.setPhUIC(cursor.getDouble(offset + 44));
        entity.setZhglsh(cursor.getDouble(offset + 45));
        entity.setKzwggl(cursor.getDouble(offset + 46));
        entity.setEdfzwggl(cursor.getDouble(offset + 47));
        entity.setYgglsh(cursor.getDouble(offset + 48));
        entity.setEdfzglsh(cursor.getDouble(offset + 49));
        entity.setZhxhgl(cursor.getDouble(offset + 50));
        entity.setEdzhxhgl(cursor.getDouble(offset + 51));
        entity.setEdzhglsh(cursor.getDouble(offset + 52));
        entity.setEdzhxl(cursor.getDouble(offset + 53));
        entity.setWgbcrl(cursor.getDouble(offset + 54));
        entity.setWgbcdrl(cursor.getDouble(offset + 55));
        entity.setEddy(cursor.getDouble(offset + 56));
        entity.setEddl(cursor.getDouble(offset + 57));
        entity.setEdxl(cursor.getDouble(offset + 58));
        entity.setEdgl(cursor.getDouble(offset + 59));
        entity.setKzgl(cursor.getDouble(offset + 60));
        entity.setKzdl(cursor.getDouble(offset + 61));
        entity.setEdglys(cursor.getDouble(offset + 62));
        entity.setWgjjdl(cursor.getDouble(offset + 63));
        entity.setDjyxzt(cursor.getDouble(offset + 64));
        entity.setDypc(cursor.getDouble(offset + 65));
        entity.setSxbphd(cursor.getDouble(offset + 66));
        entity.setMbglys(cursor.getDouble(offset + 67));
        entity.setWd(cursor.getDouble(offset + 68));
        entity.setSd(cursor.getDouble(offset + 69));
        entity.setDqy(cursor.getDouble(offset + 70));
        entity.setDate(cursor.getDouble(offset + 71));
        entity.setSavedate(cursor.getDouble(offset + 72));
        entity.setJs(cursor.getInt(offset + 73));
        entity.setLxdl(cursor.getDouble(offset + 74));
        entity.setKUA(cursor.getDouble(offset + 75));
        entity.setKUB(cursor.getDouble(offset + 76));
        entity.setKUC(cursor.getDouble(offset + 77));
        entity.setKIA(cursor.getDouble(offset + 78));
        entity.setKIB(cursor.getDouble(offset + 79));
        entity.setKIC(cursor.getDouble(offset + 80));
        entity.setHCUA(cursor.getDouble(offset + 81));
        entity.setHCUB(cursor.getDouble(offset + 82));
        entity.setHCUC(cursor.getDouble(offset + 83));
        entity.setHCIA(cursor.getDouble(offset + 84));
        entity.setHCIB(cursor.getDouble(offset + 85));
        entity.setHCIC(cursor.getDouble(offset + 86));
        entity.setBy1(cursor.getDouble(offset + 87));
        entity.setBy2(cursor.getDouble(offset + 88));
        entity.setBy3(cursor.getDouble(offset + 89));
        entity.setBy4(cursor.getDouble(offset + 90));
        entity.setBy5(cursor.getDouble(offset + 91));
        entity.setBy6(cursor.getDouble(offset + 92));
        entity.setBy7(cursor.getDouble(offset + 93));
        entity.setBy8(cursor.getDouble(offset + 94));
        entity.setBy9(cursor.getDouble(offset + 95));
        entity.setBy10(cursor.getDouble(offset + 96));
        entity.setDybb(cursor.getDouble(offset + 97));
        entity.setDlbb(cursor.getDouble(offset + 98));
        entity.setMethod(cursor.getInt(offset + 99));
        entity.setXl(cursor.getDouble(offset + 100));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TaskResEnity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TaskResEnity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TaskResEnity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
